### ISSUE TITLE
Realm: HIP build errors

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1542]
The latest control_replication does not seem to build with hip. I am seeing the following error:

```
[ 25%] Building CXX object runtime/CMakeFiles/RealmRuntime.dir/realm/threads.cc.o
[ 26%] Building CXX object runtime/CMakeFiles/RealmRuntime.dir/realm/hip/hip_module.cc.o
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/realm/hip/hip_module.cc:3560:36: error: use of undeclared identifier 'cfg_uvm_mem_size'
      config_map.insert({"uvmem", &cfg_uvm_mem_size});
```

I see cfg_uvm_mem_size is only defined for cuda. It needs to be added for hip as well.

**Comment by syamajala** [comment]
I guess there are other build errors after fixing that:
```
[  7%] Building CXX object runtime/CMakeFiles/RealmRuntime.dir/realm/deppart/partitions.cc.o                                                                                                                                                   
In file included from /lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/legion/legion_redop.cu:24:                                                                                                                    
In file included from /lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/legion.h:59:                                                                                                                                  
In file included from /lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/legion/legion_redop.h:1836:                                                                                                                   
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/legion/legion_redop.inl:141:14: error: unknown type name '__forceinline__'                                                                                          
  __device__ __forceinline__                                                                                                                                                                                                                   
             ^                                                                                                                                                                                                                                 
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/legion/legion_redop.inl:148:14: error: unknown type name '__forceinline__'                                                                                          
  __device__ __forceinline__                                                                                                                                                                                                                   
             ^                                                                                                                                                                                                                                 
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/legion/legion_redop.inl:159:14: error: unknown type name '__forceinline__'                                                                                          
  __device__ __forceinline__                                                                                                                                                                                                                   
             ^                                                                                                                                                                                                                                 
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/legion/legion_redop.inl:160:10: error: expected ';' after top level declarator                                                                                      
  uint8_t __uint2ubyte(unsigned int value, unsigned offset)                                                                                                                                                                                    
         ^                                                                                                                                                                                                                                     
         ;
```

```
[ 29%] Building CXX object runtime/CMakeFiles/RealmRuntime.dir/realm/hip/hip_access.cc.o
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/realm/hip/hip_internal.cc:1135:47: error: no member named 'hip_fold_excl_fn' in 'Realm::ReductionOpUntyped'
            (redop_info.is_exclusive ? redop->hip_fold_excl_fn : redop->hip_fold_nonexcl_fn) :
                                       ~~~~~  ^
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/realm/hip/hip_internal.cc:1135:73: error: no member named 'hip_fold_nonexcl_fn' in 'Realm::ReductionOpUntyped'
            (redop_info.is_exclusive ? redop->hip_fold_excl_fn : redop->hip_fold_nonexcl_fn) :
                                                                 ~~~~~  ^
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/realm/hip/hip_internal.cc:1136:47: error: no member named 'hip_apply_excl_fn' in 'Realm::ReductionOpUntyped'
            (redop_info.is_exclusive ? redop->hip_apply_excl_fn : redop->hip_apply_nonexcl_fn));
                                       ~~~~~  ^
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/realm/hip/hip_internal.cc:1136:74: error: no member named 'hip_apply_nonexcl_fn' in 'Realm::ReductionOpUntyped'
            (redop_info.is_exclusive ? redop->hip_apply_excl_fn : redop->hip_apply_nonexcl_fn));
                                                                  ~~~~~  ^
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/realm/hip/hip_internal.cc:1500:20: error: no member named 'hip_apply_excl_fn' in 'Realm::ReductionOpUntyped'; did you mean 'cpu_apply_excl_fn'?
        if(!redop->hip_apply_excl_fn)
                   ^~~~~~~~~~~~~~~~~
                   cpu_apply_excl_fn
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_flow_control/legion/runtime/realm/redop.h:62:14: note: 'cpu_apply_excl_fn' declared here
      void (*cpu_apply_excl_fn)(void *lhs_ptr, size_t lhs_stride,
```

**Comment by elliottslaughter** [comment]
Yes, CI is now failing on master commit 423ddfb3943c6e86cd269b045b67ba99e3463502: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/9890

It previously worked on master commit 13d4101cccc75ae67e880068617608e90fb8c3e4: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/9862

**Comment by elliottslaughter** [comment]
I'm not immediately seeing how any of this is related, but here are the commits in this range:

```console
$ git log --graph --decorate --oneline 13d4101cccc75ae67e880068617608e90fb8c3e4..423ddfb3943c6e86cd269b045b67ba99e3463502
*   423ddfb39 (HEAD -> master, origin/master, origin/HEAD) Merge branch 'rpath-fixes' into 'master'
|\  
| * 63eeeda1b (origin/rpath-fixes) Don't use lib/ blindly, ask cmake what to use
| * 110a83c35 Add libpython.so directory to BUILD_RPATH for librealm.so
| * 065d1cc05 Set RPATH on legion_python to @ORIGIN/../lib
| * 22b554eef Make sure we append to all RPATHs, instead of setting them
* 4024b4723 Merge branch 'test_args' into 'master'
* bcfd3e031 realm: update the machine_config unit test to fully test command line parser and machine config API
```

**Comment by eddy16112** [comment]
I created a fix for the hip module https://gitlab.com/StanfordLegion/legion/-/merge_requests/908, but I can not reproduce the redop error with HIP_TARGET=CUDA. the function is there https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/redop.h#L94

**Comment by elliottslaughter** [comment]
Other users are hitting this, so I went ahead and merged https://gitlab.com/StanfordLegion/legion/-/merge_requests/908. I'm not sure what to tell you about the latest NUMA failure, but hopefully this unblocks @syamajala and others.

**Comment by elliottslaughter** [comment]
New CI for `master` here: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/10240

**Comment by elliottslaughter** [comment]
Fixed the initial issue. I'll open a new bug for the NUMA one.

**Comment by elliottslaughter** [comment]
Follow-on issue is #1547.

**Comment by syamajala** [comment]
I made a local branch that merges master into control_replication and I am still not able to build on frontier. It doesnt look like the CI actually passed and failed in the prep step?

The same errors are still there.

**Comment by elliottslaughter** [comment]
I think the CI build errors are in the filesystem? It seems to be intermittent, this one passed (the build at least):

https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/10250

**Comment by elliottslaughter** [comment]
FYI, CI is passing now. The only thing that fails is #1547.

https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/10316

I'm pretty sure this is I/O instability.
