### ISSUE TITLE
url linkage from error message page

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#320]
there is an extra legion.stanford.edu/ in the url's pointing from the error message pages to the glossary of terms

**Comment by aheirich** [comment]
also check for a missing .md suffix on one of the files in either glossary or design patterns

**Comment by streichler** [comment]
@aheirich are these still issues?  If so, are they things we can clean up in the near future?  Thanks.

**Comment by elliottslaughter** [comment]
This still seems to be an issue, see e.g. https://legion.stanford.edu/messages/error_code.html#error_code_399 and then click on any of the `legion_context.cc` links. E.g. one of them goes to https://legion.stanford.edu/github.com/StanfordLegion/legion/blob/ec885f8105dc0d779bf658c6a0cc5c498c477650/runtime/legion/legion_context.cc#L9970 which is not a valid URL.

**Comment by aheirich** [comment]
I think this problem has been solved, but the online documentation still reflects the old behavior.   We just need to run doc/makeAllTheThings.bash and update the online repo.

**Comment by elliottslaughter** [comment]
I just ran the update and it's still broken. Assuming you have Jekyll and Doxygen installed, you can repro locally with:

```
git clone https://github.com/StanfordLegion/legion.stanford.edu.git jekyll
cd jekyll
make serve
```

**Comment by aheirich** [comment]
To run the update you have to go into legion/doc and execute ./makeAllTheThings.bash

Then copy the publish/* results over into the legion.stanford.edu<http://legion.stanford.edu> repo

I’m trying to do that now

On Feb 5, 2020, at 2:35 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


I just ran the update and it's still broken. Assuming you have Jekyll and Doxygen installed, you can repro locally with:

git clone https://github.com/StanfordLegion/legion.stanford.edu.git jekyll
cd jekyll
make serve

**Comment by elliottslaughter** [comment]
We run that line as part of the standard build: https://github.com/StanfordLegion/legion.stanford.edu/blob/master/Makefile#L56

**Comment by aheirich** [comment]
Then I’m perplexed.  I just ran makeAllTheThings locally and it did not reproduce the error.


On Feb 5, 2020, at 2:39 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


We run that line as part of the standard build: https://github.com/StanfordLegion/legion.stanford.edu/blob/master/Makefile#L56

**Comment by aheirich** [comment]
I just did “make serve” and it did not regenerate the messages etc.  Maybe that’s the problem.

On Feb 5, 2020, at 2:41 PM, Heirich, Alan <aheirich@slac.stanford.edu<mailto:aheirich@slac.stanford.edu>> wrote:

Then I’m perplexed.  I just ran makeAllTheThings locally and it did not reproduce the error.


On Feb 5, 2020, at 2:39 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


We run that line as part of the standard build: https://github.com/StanfordLegion/legion.stanford.edu/blob/master/Makefile#L56

**Comment by aheirich** [comment]
Ok, I think the only problem is that it was not doing “make messages” when it builds.  I just did that and verified the output is ok.

On Feb 5, 2020, at 2:46 PM, Heirich, Alan <aheirich@slac.stanford.edu<mailto:aheirich@slac.stanford.edu>> wrote:

I just did “make serve” and it did not regenerate the messages etc.  Maybe that’s the problem.

On Feb 5, 2020, at 2:41 PM, Heirich, Alan <aheirich@slac.stanford.edu<mailto:aheirich@slac.stanford.edu>> wrote:

Then I’m perplexed.  I just ran makeAllTheThings locally and it did not reproduce the error.


On Feb 5, 2020, at 2:39 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


We run that line as part of the standard build: https://github.com/StanfordLegion/legion.stanford.edu/blob/master/Makefile#L56

**Comment by elliottslaughter** [comment]
That seems to be a flaw specific to `make serve`. I pushed a change so it should update those now.

**Comment by elliottslaughter** [comment]
So I've noticed a local build does actually work. So there's something more going on here.

**Comment by elliottslaughter** [comment]
Well this is interesting:

```
<br><a href="https:/github.com/StanfordLegion/legion/blob/b32ff3becbba0876dc20ced0257243edaa342628/runtime/./legion/legion.cc#L1214">legion.cc line 1214</a>
```

Notice one slash after `https:`. Maybe that cause different behavior in the browser when it's not local?

In collate_messages.py, I see the lines:

```
if args.prefix != None:
    args.prefix = args.prefix.replace("//", "/")
```

Is this the culprit?

**Comment by elliottslaughter** [comment]
Ok, seems to be fixed by removing those lines.

**Comment by aheirich** [comment]
Ok, that line was there specifically to fix a problem where we were getting multiple //’s in the interior part of a URL.  This caused a problem of some kind that I don’t recall.  So I think the original need probably still exists, and we should fix this specifically for the case of // appearing after https:


On Feb 5, 2020, at 3:05 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, seems to be fixed by removing those lines.

**Comment by elliottslaughter** [comment]
Ok, but this is running specifically on `args.prefix` which comes into this script from the `--prefix` flag. Maybe this used to be local directory or something? It now seems to be hard-coded to Github:

```
	--prefix="https://github.com/StanfordLegion/legion/blob/${BLOB}/runtime" \
```

(inside `makeAllTheThings.bash`)

**Comment by aheirich** [comment]
It may be that this used to get parameters from a script that was inconsistent about whether a path ends in / or not.
I agree with you that if we run it only this way then the fix is bad.

On Feb 5, 2020, at 3:11 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, but this is running specifically on args.prefix which comes into this script from the --prefix flag. Maybe this used to be local directory or something? It now seems to be hard-coded to Github:

        --prefix="https://github.com/StanfordLegion/legion/blob/${BLOB}/runtime" \


(inside makeAllTheThings.bash)

**Comment by elliottslaughter** [comment]
I've temporarily deployed this fix to https://legion.stanford.edu, can you check to see if anything looks wrong?

**Comment by aheirich** [comment]
Error 399 is right now

On Feb 5, 2020, at 3:33 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


I've temporarily deployed this fix to https://legion.stanford.edu<https://legion.stanford.edu/>, can you check to see if anything looks wrong?

**Comment by lightsighter** [comment]
I don't want to close this issue until we have a concrete plan to update all the error messages here and keep them consistent with the runtime in a sane way.

**Comment by elliottslaughter** [comment]
@lightsighter What do you mean by this? The script is fully automatic and it runs every time we push the website. The underlying issue was actually one in the internal script to generate the files, and it has been fixed.

As far as I know the pages themselves are generated from parsing the source code, so there isn't really anything hard-coded into the website.

If you mean updating the error messages inside the C++ source code, I think that should be a separate issue.
