### ISSUE TITLE
Regent: non-determinism in code generation

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#334]
Regent currently produces code non-deterministically in a way that causes dynamic control replication to fail. Ideally, at least the sequence of generated runtime calls would be deterministic.

**Comment by elliottslaughter** [comment]
The easy part of this fix is now in: Regent now hashes regions by their ID, so to the extent that non-determinism comes from putting regions into hash tables, it should be fixed. Assigning to @lightsighter to confirm.

**Comment by lightsighter** [comment]
The non-determinism still exists.  Here's how to reproduce it:

1. Checkout the 'control_replication' branch
2. Build regent like this: CC_FLAGS=-DDEBUG_LEGION_COLLECTIVES ./install.py --debug --gasnet
3. Run this command: LAUNCHER="mpirun -n 2 -H localhost --oversubscribe --bind-to none -x INCLUDE_PATH -x LD_LIBRARY_PATH -x TERRA_PATH -x REALM_FREEZE_ON_ERROR" ./regent.py tests/regent/run_pass/optimize_spmd_multilevel1_2d.rg -ll:cpu 2 -fflow-spmd 1

Both processes should hit an assertion at legion_context.cc:10249 that looks like this:
terra: /home/mebauer/legion/runtime/legion/legion_context.cc:10249: Legion::Internal::CollectiveID Legion::Internal::ReplicateContext::get_next_collective_index(Legion::Internal::CollectiveIndexLocation): Assertion `location == actual_location' failed.

What this means is that the two replicated shard tasks have done runtime calls in different orders. If you look at the stack traces from the assertions you'll be able to see which runtime calls. For example, in the most recent run that I did, I see shard 0 trying to create a logical region while shard 1 is trying to create a phase barrier. My guess is that if you pretty print the code for the two top-level tasks before they run you will be able to see the different runtime calls in different orders.

Assigning back to @elliottslaughter

**Comment by lightsighter** [comment]
You should also be able to reproduce this in the master branch with -fpretty and looking at the order of the runtime calls in the pretty printed code. It's much easier to detect it though in the control replication branch where the runtime will find it for you.

I should also point out that the runtime check here is sound but not complete. It will detect when runtime calls of different kinds don't align, however, it won't be able to detect a case like this:

shard 0:
x = create_logical_region()
y = create_logical_region()

shard 1:
y = create_logical_region()
x = create_logical_region()

So be careful of such cases in your generated code because the runtime will think that those are just fine when in practice they will actually cause all sorts of problems.

**Comment by lightsighter** [comment]
This is now the only failing regent test case in the control replication branch. (I think there could be more though if we had annotations on marking a task 'replicable'.)

**Comment by elliottslaughter** [comment]
This has been fixed in a new branch called `deterministic`. This is in a branch because it breaks the auto-parallelizer. With the fixes, you can observe that the code (via `-fpretty 1`) is identical in multi-node runs (it produces an empty diff). However, it appears that there is still a shutdown crash.

Assigning back to @lightsighter to confirm and to @magnatelee to fix the parallelizer.

**Comment by elliottslaughter** [comment]
@magnatelee FYI the changes are that the region universe and the constraints are created via `data.newmap()` and `data.new_recursive_map(2)`, respectively. That means you can't use `pairs()` and `rawget()` etc. on these objects anymore, and if you want to copy them, you need to use `:copy()` instead of rolling your own. Somehow the parallelizer is generating code that is breaking subsequent passes, so it's probably not respecting this somehow.

**Comment by lightsighter** [comment]
@elliottslaughter Is the `deterministic` branch downstream of the `control_replication` branch or is it just downstream of `master`?

**Comment by elliottslaughter** [comment]
`deterministic` is downstream of master only.

**Comment by elliottslaughter** [comment]
Now tracking test status in #339. Will merge that PR once the tests are passing.

**Comment by elliottslaughter** [comment]
Merged. Assigning to @lightsighter to confirm.

**Comment by lightsighter** [comment]
Verified that this works now on the control replication branch. Closing the issue for now. Will re-open it if we encounter any future kinds of non-determinism that occur in Regent code generation.
