### ISSUE TITLE
Regent: partitioning equally by sparse index space throws assertion

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#483]
Partitioning equally by a sparse index space causes the following assertion:
`terra: /home/seshu/dev/legion/runtime/legion/legion_domain.inl:1015: Legion::Domain::operator Legion::Rect<DIM, T>() const [with int DIM = 3; T = long long int]: Assertion is_id == 0 failed.`

Here is an example:
```
import "regent"

local c = regentlib.c

task main()
  var blocks = region(ispace(int3d, {31, 31, 64}, {1, 1, 0}), int1d)

  blocks[{1, 1, 0}] = 1

  for i = 0, 16 do
    blocks[{25, 25, i}] = 1
  end

  for i = 0, 64 do
    blocks[{31, 31, i}] = 1
  end

  var allocated_blocks_part = partition(blocks, ispace(int1d, 2))
  var allocated_blocks_ispace = allocated_blocks_part[1].ispace

  var clusters = region(allocated_blocks_ispace, rect2d)
  fill(clusters, rect2d{lo = int2d{-1, -1}, hi = int2d{-1, -1}})
  var clusters_part = partition(equal, clusters, clusters.ispace)
end

regentlib.start(main)
```

Attached is a stack trace from gdb. 
[gdb.txt](https://github.com/StanfordLegion/legion/files/2880273/gdb.txt)

Printing the values of d and r here: 
https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion_c.cc#L125
results in:
```
d = {is_id = 4611686018427387906, dim = 3, rect_data = {1, 1, 0, 31, 31, 63}}
r = {<Realm::Rect<3, long long>> = {lo = {x = 31, y = 63, z = 4611686018427387906}, hi = {x = 7652285353445118208, y = 433791696897,
      z = 140736416712792}}, <No data fields>}
```

**Comment by magnatelee** [comment]
So this is actually caused by the compiler; the compiler always tries to extract a dense rectangle from the color space and this doesn't work when the color space is sparse. I just pushed a change (https://gitlab.com/StanfordLegion/legion/commit/15e9925811a6c31bf14e3738b3e29bfd00a6a5f3) that emits a direct Realm call when the color space is sparse, and this is the error message that Seshu should have seen: (which basically means Realm has an unimplemented case)
```
legion/runtime/realm/deppart/partitions.cc:149: Realm::Event Realm::IndexSpace<N, T>::create_equal_subspaces(size_t, size_t, std::vector<Realm::IndexSpace<N, T> >&, const Realm::ProfilingRequestSet&, Realm::Event) const [with int N = 3; T = long long int; size_t = long unsigned int]: Assertion '0' failed.
```

**Comment by streichler** [comment]
Commit 284a71b should provide this functionality.

**Comment by streichler** [comment]
@syamajala can you provide an update on this?  Did the combination of the regent and realm fixes take care of this, or is there still an issue?

**Comment by syamajala** [comment]
Seems to be working.
