### ISSUE TITLE
Differences between PyPy and CPython in Legion Prof generated output

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#547]
PyPy and CPython (i.e. the normal Python implementation) generate different output when running the Legion Prof script. It's nice to be able to use PyPy because it is substantially faster than CPython for many operations.

I'm attaching an example log and `legion_prof` output from PyPy and CPython. The PyPy output has extra lines for each processor: each processor appears under its node *and also up above in a section independent from any node*. This makes the charts take up quite a bit of space when there are many nodes.

[legion_prof_comparison.tar.gz](https://github.com/StanfordLegion/legion/files/3277940/legion_prof_comparison.tar.gz)

```
$ python -V
Python 2.7.12
$ pypy -V
Python 2.7.10 (5.1.2+dfsg-1~16.04, Jun 16 2016, 17:37:42)
[PyPy 5.1.2 with GCC 5.3.1 20160413]
```

**Comment by lightsighter** [comment]
It looks like @seemamirch fixed this with f48c6062. I see the extra profiling lines are gone, but the names of the individual memory channels are still not rendering correctly. I just see things like "node[0] to node[0]". If you hover over them you see the right memories listed, but it's not obvious from the label that this channel is between two memories. @elliottslaughter can you confirm you're seeing both the fix and the same issue I am seeing for your log file?

Assigning @seemamirch for the bug for now.

**Comment by elliottslaughter** [comment]
I'm still seeing both problems in the latest master (26cd55afb795ea84015b5f20a10cb99a71f8050d).

**Comment by elliottslaughter** [comment]
I confirmed that with the PyPy on Sapling (which is newer) the issue with extra processors go away. I still see the issue Mike identified.

```
$ pypy -V
Python 2.7.13 (5.8.0+dfsg-2~ppa2~ubuntu14.04, Jun 17 2017, 18:51:40)
[PyPy 5.8.0 with GCC 4.8.4]
```

Given that it works in a newer PyPy version I think it's not worth worrying about older PyPy version.

**Comment by seemamirch** [comment]
I'm also not able to reproduce this. I did fix it a while back
https://gitlab.com/StanfordLegion/legion/commit/5fa02ac11ad9da7ce735688aedc265fb29f1d852
Also the node[0] to node[0] was by design i.e. where do the memories resides. It is grouped under (Channels) + hovering over it gives you the details.  Previously it was not grouped under channels and the title was always "Mem to Men Channel". But if it's not intuitive I can change it to something else.

**Comment by lightsighter** [comment]
Well, the node[0] to node[0] is a problem on things like DGX boxes. Inside of a single node there are actually 80 channels: 64 because there is a channel between each pair of the 8 GPUs, and 16 more because there is a channel between each of the 2 CPUs and each of the 8 GPUs. We don't want all those channels to show up the same as "node[0] to node[0]". We actually need to see the names of the memories.

**Comment by lightsighter** [comment]
Also, I think I see filenames with "L" in them in the legion_prof_processors.tsv file when I run with pypy.

**Comment by seemamirch** [comment]
So it does report the GPU if the memory resides on it example node[0][GPU 8] (frame buffer on gpu8). Hovering over it - will give the details.
If it's just sys mem is says node[0]. Let me know what exactly you want it to say.
That "L" was fixed a while back

**Comment by lightsighter** [comment]
How do you distinguish between framebuffer and zero-copy memories on the same GPU?

> That "L" was fixed a while back
I think @elliottslaughter and I are still seeing them so maybe they are not fixed everywhere?

**Comment by elliottslaughter** [comment]
I am no longer able to reproduce the issue with `L` since I upgrade PyPy on my desktop to version 7.0.0.

**Comment by lightsighter** [comment]
It seems that my problem is also an old pypy. I think @seemamirch has also updated the labels for the channels so I think we can close this if @elliottslaughter is satisfied.

**Comment by seemamirch** [comment]
I'll close it once I check it in - here's a version for preview (I will replace [node 0] with n0 too) http://sapling.stanford.edu/~seemah/legion_june/examples/circuit/legion_prof.23/?start=5393150.430480174&end=5585545.156940655&collapseAll=false&resolution=10

**Comment by elliottslaughter** [comment]
Everything looks fine from my end.

**Comment by seemamirch** [comment]
Checked in the changes to master
