### ISSUE TITLE
Legion: Tracing causes different behavior between runs

### ISSUE THREAD

**Issue by stevenrbrill** [StanfordLegion/legion#770]
In the CFD code we are developing, we are using tracing around our timestepping loop. However we are seeing different results each run (which is most easily found in the fact that our simulation goes unstable at different timesteps each time. This only occurs when `-dm:memoize` is used. Otherwise the solution is consistent.

Also, this issue only occurs when Legion is built with Gasnet (even if only a single node is used for the run.).

**Comment by lightsighter** [comment]
Also worth noting that I have observed a similar behavior with Pennant, but in my case I only see it show up around 128 GPUs across 16 nodes. Symptoms are similar though.

> Also, this issue only occurs when Legion is built with Gasnet (even if only a single node is used for the run.).

Do you run with multiple processes per node or just one process on a single node?

**Comment by stevenrbrill** [comment]
I am running with -ppn 1 in the mpiexec command, but would like it to use all the processors per node, which Legion is taking care of.

**Comment by magnatelee** [comment]
This should be fixed by f0501bdc. @stevenrbrill Can you pull master and try again?

**Comment by stevenrbrill** [comment]
This commit has not solved our issue. What kind of backlogs would help figure out the issue?

**Comment by mariodirenzo** [comment]
I think that I am observing this issue in my solver too.
One of the regression tests fails non-deterministically if tracing is active.
The issue can be reproduced on a single node. It just needs the computational domain (main region) to be partitioned.
Please, let me know if I can produce debug logs

**Comment by lightsighter** [comment]
@magnatelee and I know what the problem is and fix is in the work. @magnatelee will comment here once it is pushed to the master branch.

**Comment by magnatelee** [comment]
This should be fixed as of a923f1b6. @stevenrbrill can you pull and try again?
