### ISSUE TITLE
Regent: -fcuda-offline 1 seems broken

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#956]
I'm getting in the following error
```
legion/language/terra.build/src/terralib.lua:4263: error loading terra module util-desugared from file util-desugared.rg:
	llvm: libcuda.so.1: cannot open shared object file: No such file or directory

stack traceback:
	...cfd/direnzo/legion/language/terra.build/src/terralib.lua:4384: in function 'linklibrary'
	/scratch/cfd/direnzo/legion/language/src/regent/std_base.t:64: in main chunk
	[C]: in function 'require'

�
	...h/cfd/direnzo/legion/language/src/regent/affine_helper.t:17: in main chunk
	[C]: in function 'require'
	/scratch/cfd/direnzo/legion/language/src/regent/std.t:17: in main chunk
	[C]: in function 'require'
	/scratch/cfd/direnzo/legion/language/src/regent/builtins.t:17: in main chunk
	[C]: in function 'require'
	/scratch/cfd/direnzo/legion/language/src/regent.t:21: in main chunk
	[C]: at function: 0x2b25bae38fa0
	[C]: in function 'xpcall'
	...cfd/direnzo/legion/language/terra.build/src/terralib.lua:4400: in function <...cfd/direnzo/legion/language/terra.build/src/terralib.lua:4399>
	[C]: in function 'loadfile'
	...cfd/direnzo/legion/language/terra.build/src/terralib.lua:4264: in function <...cfd/direnzo/legion/language/terra.build/src/terralib.lua:4249>
	[C]: in function 'require'
	process_schema.rg:7: in main chunk
stack traceback:
	[C]: in function 'error'
	...cfd/direnzo/legion/language/terra.build/src/terralib.lua:4263: in function <...cfd/direnzo/legion/language/terra.build/src/terralib.lua:4263>
	[C]: in function 'require'
	process_schema.rg:7: in main chunk
```
when compiling a Regent script with the following command line
```
legion/language/regent.py process_schema.rg config_schema.lua -fflow 0 -finner 1 -fopenmp 1 -fcuda 1 -fcuda-offline 1
```

My understanding is that `-fcuda-offline` should force Regent not to load the CUDA library. Is that correct? Is there any workaround other than submitting a job on the gpu nodes of the machine to compile the code?

**Comment by manopapad** [comment]
This is not related to `-fcuda-offline`. The Regent compiler is just trying to load the Regent bindings library `libregent.so` (https://github.com/StanfordLegion/legion/blob/stable/language/src/regent/std_base.t#L64), and that load is failing because this library was compiled with GPU support and thus links against `libcuda.so`, which is not available on the head node. This is just a linking issue, the compiler isn't trying to use CUDA functionality at the time of the crash.

Normally the bindings library is only needed at runtime, but it can also be useful during compilation for things like timing calls, and of course it's necessary if you want to compile and run in one go. However, having written `process_schema.rg` I know for a fact it stays away from features of the compiler that require the bindings library at compilation time. A short-term fix would be to comment-out these lines https://github.com/StanfordLegion/legion/blob/stable/language/src/regent/std_base.t#L63-L65. A long-term fix would be for Regent to load this library on demand.

**Comment by magnatelee** [comment]
@mariodirenzo @manopapad 's assessment is correct. The issue happens when the compiler tries to load the binding library and doesn't have anything to do with the offline cuda code generation itself. I was actually working on the fix and will soon push it.

**Comment by magnatelee** [comment]
This issue should be fixed as of 890f9a81, which will be propagated to the `control_replication` branch once it passes the CI tests. With this change, you should now use `-foffline 1` (which will supersede `-fcuda-offline` and `-fopenmp-offline`) to compile the regent code in "offline" mode. Inline execution (i.e., calling `regentlib.start`) is disallowed in the offline mode, and you must replace all your uses of `terralib.linklibrary` with `regentlib.linklibrary` and must not compile any regent tasks or terra functions by manually calling the `compile` method. Give this a try and let me know if it doesn't work for you.

**Comment by mariodirenzo** [comment]
Thanks for creating the new flag. `-foffline 1` fixes the issues with the regent compiler but the `libregent.so` is still not linked to the stub libraries, therefore the linking of the executable still needs to be executed on the computational nodes. Would it be possible to have  `libregent.so` to point to the stub cuda libraries?

**Comment by manopapad** [comment]
We probably don't want `libregent.so` to point directly to the stubs, because `libregent.so` also needs to be linked with the program at runtime, and we would want to link to the actual CUDA library then. Can you try adding `-L/path/to/stubs/dir` to the link command before `-lregent`? I believe this will let the static linker use the stubs, but the dynamic linker will still pick up the actual libraries.

**Comment by mariodirenzo** [comment]
I tried adding the stubs path to the link command but it does not have any effect

**Comment by manopapad** [comment]
Can you post the link command you're using, and the output you get?

**Comment by mariodirenzo** [comment]
The command line looks like this
```
g++ -o averageTest.exec averageTest.o /scratch/cfd/direnzo/htr/src/config_schema.o /scratch/cfd/direnzo/htr/src/json.o -L/scratch/cfd/direnzo/legion/bindings/regent -L/softs/nvidia/cuda-10.1/lib64/stubs -lregent -L/scratch/cfd/direnzo/legion/language/hdf/install/lib -lhdf5 -lm
```
and the error looks like
```
/usr/bin/ld: warning: libcuda.so.1, needed by /scratch/cfd/direnzo/legion/bindings/regent/libregent.so, not found (try using -rpath or -rpath-link)
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuMemFree_v2'
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuCtxPushCurrent_v2'
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuMemsetD32Async'
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuEventCreate'
[...]
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuOccupancyMaxActiveBlocksPerMultiprocessor'
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuStreamDestroy_v2'
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuCtxSetSharedMemConfig'
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: undefined reference to `cuMemsetD8Async'
```

The error is the same with and without `-L/softs/nvidia/cuda-10.1/lib64/stubs`

**Comment by manopapad** [comment]
Could you please execute the following commands:

```
file ???.so
ldd ???.so
nm -D ???.so | grep cuMemFree_v2
readelf ???.so -d
```

for each of:

```
LEGION_DIR/bindings/regent/libregent.so
"real" libcuda.so (and all libcuda.so.*)
stubs libcuda.so (and all libcuda.so.*)
```

**Comment by mariodirenzo** [comment]
The outputs are:

- for legion/bindings/regent/libregent.so:
```
/scratch/cfd/direnzo/legion/bindings/regent/libregent.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, not stripped
	linux-vdso.so.1 =>  (0x00007fff241a0000)
	librt.so.1 => /lib64/librt.so.1 (0x00002ac62b23f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ac62b447000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002ac62b663000)
	libcuda.so.1 => not found
	libpsm2.so.2 => /lib64/libpsm2.so.2 (0x00002ac62b867000)
	libpmi2.so.0 => /lib64/libpmi2.so.0 (0x00002ac62bafb000)
	libhdf5.so.101 => /scratch/cfd/direnzo/legion/language/hdf/install/lib/libhdf5.so.101 (0x00002ac62bd14000)
	libmpi.so.40 => /softs/local/openmpi/3.1.5_gcc54/lib/libmpi.so.40 (0x00002ac62c2da000)
	libz.so.1 => /lib64/libz.so.1 (0x00002ac62c5d8000)
	libstdc++.so.6 => /softs/local/gcc/5.4.0/lib64/libstdc++.so.6 (0x00002ac62c7ee000)
	libm.so.6 => /lib64/libm.so.6 (0x00002ac62cb69000)
	libgcc_s.so.1 => /softs/local/gcc/5.4.0/lib64/libgcc_s.so.1 (0x00002ac62ce6b000)
	libc.so.6 => /lib64/libc.so.6 (0x00002ac62d082000)
	/lib64/ld-linux-x86-64.so.2 (0x00002ac628c66000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00002ac62d44f000)
	libopen-rte.so.40 => /softs/local/openmpi/3.1.5_gcc54/lib/libopen-rte.so.40 (0x00002ac62d65b000)
	libopen-pal.so.40 => /softs/local/openmpi/3.1.5_gcc54/lib/libopen-pal.so.40 (0x00002ac62d911000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002ac62dc16000)
                 U cuMemFree_v2

Dynamic section at offset 0x216e6d0 contains 38 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcuda.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpsm2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpmi2.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5.so.101]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [/softs/nvidia/cuda-10.1/lib64:/softs/local/openmpi/3.1.5_gcc54/lib]
 0x000000000000000c (INIT)               0x502db0
 0x000000000000000d (FINI)               0x19314ec
 0x0000000000000019 (INIT_ARRAY)         0x2323c70
 0x000000000000001b (INIT_ARRAYSZ)       992 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x2324050
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x1c8
 0x0000000000000005 (STRTAB)             0xde320
 0x0000000000000006 (SYMTAB)             0x2d938
 0x000000000000000a (STRSZ)              3027772 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x2378000
 0x0000000000000002 (PLTRELSZ)           290592 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x4bbe90
 0x0000000000000007 (RELA)               0x3d03c0
 0x0000000000000008 (RELASZ)             965328 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x3d01e0
 0x000000006fffffff (VERNEEDNUM)         9
 0x000000006ffffff0 (VERSYM)             0x3c165c
 0x000000006ffffff9 (RELACOUNT)          15537
 0x0000000000000000 (NULL)               0x0
```
- for real libcuda.so (available only on compute nodes):
```
/lib64/libcuda.so.1
/lib64/libcuda.so.1: symbolic link to `libcuda.so.418.87.00'
	linux-vdso.so.1 =>  (0x00007fff795fe000)
	libm.so.6 => /lib64/libm.so.6 (0x00002abfdf1c5000)
	libc.so.6 => /lib64/libc.so.6 (0x00002abfdf4c7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002abfdf894000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002abfdfa98000)
	librt.so.1 => /lib64/librt.so.1 (0x00002abfdfcb4000)
	libnvidia-fatbinaryloader.so.418.87.00 => /lib64/libnvidia-fatbinaryloader.so.418.87.00 (0x00002abfdfebc000)
	/lib64/ld-linux-x86-64.so.2 (0x00002abfdde2a000)
000000000025d1f0 T cuMemFree_v2

Dynamic section at offset 0xe58600 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libnvidia-fatbinaryloader.so.418.87.00]
 0x000000000000000e (SONAME)             Library soname: [libcuda.so.1]
 0x0000000000000010 (SYMBOLIC)           0x0
 0x000000000000000c (INIT)               0xc91b8
 0x000000000000000d (FINI)               0x3d8e98
 0x0000000000000004 (HASH)               0x158
 0x0000000000000005 (STRTAB)             0x5768
 0x0000000000000006 (SYMTAB)             0x14a8
 0x000000000000000a (STRSZ)              12693 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x105c870
 0x0000000000000002 (PLTRELSZ)           6264 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xc7940
 0x0000000000000007 (RELA)               0x8f30
 0x0000000000000008 (RELASZ)             780816 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x8e90
 0x000000006fffffff (VERNEEDNUM)         5
 0x000000006ffffff0 (VERSYM)             0x88fe
 0x000000006ffffff9 (RELACOUNT)          32521
 0x0000000000000000 (NULL)               0x0
```

- for stubs libcuda.so:
```
/softs/nvidia/cuda-10.1/lib64/stubs/libcuda.so
/softs/nvidia/cuda-10.1/lib64/stubs/libcuda.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
	linux-vdso.so.1 =>  (0x00007ffc287a6000)
	libstdc++.so.6 => /softs/local/gcc/5.4.0/lib64/libstdc++.so.6 (0x00002b3897429000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b38977a4000)
	libgcc_s.so.1 => /softs/local/gcc/5.4.0/lib64/libgcc_s.so.1 (0x00002b3897aa6000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b3897cbd000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b3896ff9000)
0000000000006590 T cuMemFree_v2

Dynamic section at offset 0xb4a8 contains 25 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libcuda.so.1]
 0x0000000000000010 (SYMBOLIC)           0x0
 0x000000000000000c (INIT)               0x6130
 0x000000000000000d (FINI)               0x7db8
 0x000000006ffffef5 (GNU_HASH)           0x158
 0x0000000000000005 (STRTAB)             0x3838
 0x0000000000000006 (SYMTAB)             0xe68
 0x000000000000000a (STRSZ)              9442 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x20b690
 0x0000000000000002 (PLTRELSZ)           24 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x6118
 0x0000000000000007 (RELA)               0x60b8
 0x0000000000000008 (RELASZ)             96 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x6098
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x5d1a
 0x000000006ffffff9 (RELACOUNT)          1
 0x0000000000000000 (NULL)               0x0
```

**Comment by manopapad** [comment]
Can you try one of these two solutions?

1. Make a link to the stub libcuda.so named libcuda.so.1 (the same name that libregent.so is looking for):

```
cd <some-dir-you-have-write-access-to>
ln -s /softs/nvidia/cuda-10.1/lib64/stubs/libcuda.so libcuda.so.1
``` 

Then run the link step with `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<some-dir-you-have-write-access-to>`. Apparently even while compiling, when a dynamic library needs to resolve its dependencies it asks the dynamic linker, and the dynamic linker reads the value of LD_LIBRARY_PATH. During execution the libcuda.so.1 library is at a well-known location, so you don't need to edit LD_LIBRARY_PATH.

2. Preemptively link with the stub libcuda.so; pass link flags in this order: `-L/softs/nvidia/cuda-10.1/lib64/stubs/ -lcuda -lregent`. This might have the unintended consequence that the application gets a hardcoded link to the stub libcuda.so and will use that during execution, instead of looking for the real libcuda.so.

**Comment by manopapad** [comment]
Did any of the above work for you?

**Comment by mariodirenzo** [comment]
Hi @manopapad,
I'm sorry I forgot to answer this thread. The solution 1 fixes the issue, though I do not know if that is the log term fix that should be applied.

**Comment by manopapad** [comment]
This message `ERROR: unrecognized lowlevel option: -ll:gpu` usually means that libregent.so was compiled without CUDA support. Can you confirm that you set `USE_CUDA=1` or something equivalent when compiling this libregent.so?

**Comment by mariodirenzo** [comment]
Yes, if I just re-link the executable with the standard library (on a computer node), the code works fine

**Comment by manopapad** [comment]
Can you try linking on the head node without using the stubs (i.e. don't update `LD_LIBRARY_PATH` as in option 1 above), but use `-Wl,-unresolved-symbols=ignore-in-shared-libs` in the linker command?

**Comment by mariodirenzo** [comment]
That works fine, though it is not very safe

**Comment by manopapad** [comment]
We're trying to link against a dynamic library that's not present, so anything we do will be unsafe to some degree.

At this point I think we've solved all the problems you've reported, so I'm closing this issue. Feel free to reopen if that's not the case.
